### ISSUE TITLE
Misleading error message on event edit

### ISSUE THREAD

**Issue by jcolson** [jcolson/dndvault-bot#228]
![Screenshot_20210517-071140](https://user-images.githubusercontent.com/2362647/118446611-ba0c4900-b6e7-11eb-8650-d6ab23cf5723.jpg)
```[2021-05-16T20:42:19.299Z] [shrd:0] handleEventEdit: Error: Unknown event id (609310cd0ecd2b001482fl24) For Channel: 826746054916440077
    at bc_eventEdit (/usr/src/bot/handlers/events.js:150:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.handleEventEdit (/usr/src/bot/handlers/events.js:103:31)
[2021-05-16T20:43:21.390Z] [shrd:0] handleEventEdit: Error: Not enough parameters, you need to pass at least one editable parameter.
    at Object.handleEventEdit (/usr/src/bot/handlers/events.js:95:19)
    at handleCommandExec (/usr/src/bot/bot.js:939:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async WebSocketManager.<anonymous> (/usr/src/bot/bot.js:795:9)
[2021-05-16T20:44:35.298Z] [shrd:0] handleEventEdit: Error: Not enough parameters, you need to pass at least one editable parameter.
    at Object.handleEventEdit (/usr/src/bot/handlers/events.js:95:19)
    at handleCommandExec (/usr/src/bot/bot.js:939:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async WebSocketManager.<anonymous> (/usr/src/bot/bot.js:795:9)
```

**Comment by jcolson** [comment]
false alarm, the value passed was, indeed, invalid
