### ISSUE TITLE
exception occuring in sendReminders

### ISSUE THREAD

**Issue by jcolson** [jcolson/dndvault-bot#299]
`[2021-06-15T17:10:02.341Z] [shrd:0] sendReminders TypeError: Cannot read property 'slice' of undefined
    at Function.idToBinary (/usr/src/bot/node_modules/discord.js/src/util/Util.js:503:29)
    at Function.deconstruct (/usr/src/bot/node_modules/discord.js/src/util/Snowflake.js:66:25)
    at Message._patch (/usr/src/bot/node_modules/discord.js/src/structures/Message.js:140:43)
    at new Message (/usr/src/bot/node_modules/discord.js/src/structures/Message.js:44:20)
    at Object.sendReminders (/usr/src/bot/handlers/events.js:1020:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
`

**Comment by jcolson** [comment]
somehow an event doesn't have a messageID:
`_id
:
60c11b2b1cfc4700138f733d
guildID
:
"852266636765298709"
userID
:
"679140275733659669"
attendees
:
date_time
:
2021-06-15T18:00:00.000+00:00
title
:
"Session"
dm
:
"679140275733659669"
duration_hours
:
3
number_player_slots
:
8
description
:
"Regular Session"
recurEvery
:
7
__v
:
1
reminderSent
:
2021-06-15T17:10:02.226+00:00`

**Comment by jcolson** [comment]
avoiding the race condition that most likely caused the messageID not to be saved.  avoiding it 'double time' now that sendMessages, recurEvents, removeOldSessionPlanningChannels, removeOldSessionVoiceChannels are all 'awaited' from bot.js
