### ISSUE TITLE
obscure error message returned when event id is not correct for event_signup and event_withdrawal

### ISSUE THREAD

**Issue by jcolson** [jcolson/dndvault-bot#300]
`[2021-06-16T07:53:30.343Z] [shrd:0] handleEventSignup: CastError: Cast to ObjectId failed for value "test" at path "_id" for model "Event"
    at model.Query.exec (/usr/src/bot/node_modules/mongoose/lib/query.js:4408:21)
    at model.Query.Query.then (/usr/src/bot/node_modules/mongoose/lib/query.js:4502:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  messageFormat: undefined,
  stringValue: '"test"',
  kind: 'ObjectId',
  value: 'test',
  path: '_id',
  reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
      at new ObjectID (/usr/src/bot/node_modules/bson/lib/bson/objectid.js:59:11)
      at castObjectId (/usr/src/bot/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/usr/src/bot/node_modules/mongoose/lib/schema/objectid.js:279:12)
      at ObjectId.SchemaType.applySetters (/usr/src/bot/node_modules/mongoose/lib/schematype.js:1104:12)
      at ObjectId.SchemaType._castForQuery (/usr/src/bot/node_modules/mongoose/lib/schematype.js:1539:15)
      at ObjectId.SchemaType.castForQuery (/usr/src/bot/node_modules/mongoose/lib/schematype.js:1529:15)
      at ObjectId.SchemaType.castForQueryWrapper (/usr/src/bot/node_modules/mongoose/lib/schematype.js:1506:20)
      at cast (/usr/src/bot/node_modules/mongoose/lib/cast.js:331:32)
      at model.Query.Query.cast (/usr/src/bot/node_modules/mongoose/lib/query.js:4848:12)
      at model.Query.Query._castConditions (/usr/src/bot/node_modules/mongoose/lib/query.js:1890:10)
      at model.Query.<anonymous> (/usr/src/bot/node_modules/mongoose/lib/query.js:2147:8)
      at model.Query._wrappedThunk [as _findOne] (/usr/src/bot/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at /usr/src/bot/node_modules/kareem/index.js:370:33
      at processTicksAndRejections (node:internal/process/task_queues:76:11)
}
[2021-06-16T07:53:30.342Z] [shrd:0] msg processed:INTERACTION:Test and Support - D&D Vault:blackntan#0069(Jay (BST)):event_signup:[{"value":"test","type":3,"name":"event_id"},{"value":"227562842591723521","type":6,"name":"user_id"}]
`

**Comment by jcolson** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/2362647/122180753-9ff98e00-ce80-11eb-8e1f-d505aef1d2df.png">
